# Generated by Django 5.2.8 on 2026-06-23 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lottery', '0002_drawresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('intro', '玩法说明'), ('rule', '奖级规则'), ('activity', '活动公告')], default='intro', max_length=12, verbose_name='类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lottery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='lottery.lottery', verbose_name='彩种')),
            ],
            options={
                'verbose_name': '玩法介绍',
                'verbose_name_plural': '玩法介绍',
                'ordering': ['sort', '-publish_at'],
            },
        ),
    ]
