# Generated by Django 5.2.8 on 2026-06-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playguide',
            options={'ordering': ['sort', '-publish_at'], 'verbose_name': '玩法说明', 'verbose_name_plural': '玩法说明'},
        ),
        migrations.AddField(
            model_name='playguide',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='重要通知'),
        ),
        migrations.AlterField(
            model_name='playguide',
            name='type',
            field=models.CharField(choices=[('intro', '玩法说明'), ('rule', '奖级规则'), ('activity', '活动公告'), ('notice', '通知公告')], default='intro', max_length=12, verbose_name='类型'),
        ),
    ]
