# Generated by Django 5.2.8 on 2026-06-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='用户哈希')),
                ('path', models.CharField(max_length=100, verbose_name='路径')),
                ('lottery_code', models.CharField(blank=True, default='', max_length=20, verbose_name='彩种')),
                ('action', models.CharField(default='view', max_length=20, verbose_name='动作')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '访问日志',
                'verbose_name_plural': '访问日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
