# Generated by Django 5.2.8 on 2026-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='彩种标识')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('category', models.CharField(choices=[('福彩', '福彩'), ('体彩', '体彩')], max_length=10, verbose_name='类别')),
                ('rule_config', models.JSONField(default=dict, verbose_name='号码规则')),
                ('draw_days', models.JSONField(default=list, verbose_name='开奖星期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '彩种',
                'verbose_name_plural': '彩种',
            },
        ),
    ]
