# Generated by Django 5.2.8 on 2026-06-22 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=20, verbose_name='期号')),
                ('draw_date', models.DateField(verbose_name='开奖日期')),
                ('numbers', models.JSONField(default=dict, verbose_name='开奖号码')),
                ('sales_amount', models.CharField(blank=True, default='', max_length=30, verbose_name='销售额')),
                ('pool_amount', models.CharField(blank=True, default='', max_length=30, verbose_name='奖池金额')),
                ('prize_grades', models.JSONField(default=list, verbose_name='各奖级')),
                ('source', models.CharField(choices=[('crawler', '爬虫'), ('manual', '人工')], default='crawler', max_length=10, verbose_name='来源')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=10, verbose_name='状态')),
                ('updated_by', models.CharField(blank=True, default='', max_length=50, verbose_name='最后修改人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='lottery.lottery', verbose_name='彩种')),
            ],
            options={
                'verbose_name': '开奖结果',
                'verbose_name_plural': '开奖结果',
                'ordering': ['-draw_date', '-issue'],
                'unique_together': {('lottery', 'issue')},
            },
        ),
    ]
