# Generated by Django 5.2.8 on 2026-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_drawresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawresult',
            name='prize_area',
            field=models.TextField(blank=True, default='', verbose_name='一等奖分省'),
        ),
    ]
