# Generated by Django 5.2.8 on 2026-07-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_drawresult_prize_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='draw_time',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='开奖时间'),
        ),
    ]
