# Generated by Django 5.2.8 on 2026-06-22 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lottery', '0002_drawresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='用户哈希')),
                ('numbers', models.JSONField(default=dict, verbose_name='号码')),
                ('gen_type', models.CharField(choices=[('manual', '手动'), ('random', '机选'), ('dan_random', '定胆随机')], default='manual', max_length=12, verbose_name='生成方式')),
                ('dan_numbers', models.JSONField(blank=True, default=dict, verbose_name='胆码')),
                ('note', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('target_issue', models.CharField(blank=True, default='', max_length=20, verbose_name='目标期号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_numbers', to='lottery.lottery', verbose_name='彩种')),
            ],
            options={
                'verbose_name': '用户号码',
                'verbose_name_plural': '用户号码',
                'ordering': ['-created_at'],
            },
        ),
    ]
