# Generated by Django 5.2.8 on 2026-06-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usernumber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernumber',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='分组'),
        ),
    ]
