# Generated by Django 5.2.8 on 2026-06-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usernumber', '0002_usernumber_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='用户哈希')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'ordering': ['-created_at'],
            },
        ),
    ]
