# Generated by Django 5.2.8 on 2026-06-25 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_drawresult_prize_area'),
        ('usernumber', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='用户哈希')),
                ('issue', models.CharField(max_length=20, verbose_name='期号')),
                ('numbers', models.JSONField(default=dict, verbose_name='号码')),
                ('bet_count', models.PositiveIntegerField(default=1, verbose_name='注数')),
                ('purchase_date', models.DateField(verbose_name='购买日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='lottery.lottery', verbose_name='彩种')),
            ],
            options={
                'verbose_name': '购买记录',
                'verbose_name_plural': '购买记录',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
