# Generated by Django 5.2.8 on 2026-06-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usernumber', '0004_purchaserecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='用户哈希')),
                ('openid', models.CharField(max_length=128, unique=True, verbose_name='openid')),
                ('nickname', models.CharField(blank=True, default='', max_length=30, verbose_name='昵称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
        ),
    ]
