# Generated by Django 5.2.8 on 2026-06-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usernumber', '0005_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='unionid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='unionid'),
        ),
    ]
