# Generated by Django 5.2.8 on 2026-06-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usernumber', '0006_appuser_unionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='home_lotteries',
            field=models.JSONField(blank=True, default=list, verbose_name='首页彩种'),
        ),
    ]
